version: '3.8'
services:
  server:
    build:
      context: "./server"
      dockerfile: "Dockerfile"
    image: "todo-server"
    env_file:
      - "./server/.env"
    ports:
      - "3000:3000"

  client:
    build:
      context: "./client"
      dockerfile: 'Dockerfile'
    image: "todo-client"
    ports:
      - "3001:3001"     
      - "80:80" 

  mongo_db:
    image: mongo:7.0.10-rc0-jammy
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"     

volumes:
  mongodb_data: