version: '3.8'
services:
  server:
    build:
      context: "./server"
      dockerfile: "Dockerfile"
    image: "todo-server"
    env_file:
      - "./server/.env"
    ports:
      - "3000:3000"

  client:
    build:
      context: "./client"
      dockerfile: 'Dockerfile'
    image: "todo-client"
    ports:
      - "3001:3001"      